server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Stacktraces niemals im Browser anzeigen
server.error.include-stacktrace=never
# Detaillierte Fehlermeldungen ausschalten
server.error.include-message=never

app.version=@project.version@

spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker=ERROR