server.servlet.encoding.charset=UTF-8
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Stacktraces niemals im Browser anzeigen
server.error.include-stacktrace=never
# Detaillierte Fehlermeldungen ausschalten
server.error.include-message=never

app.version=@project.version@

# Deaktiviert das Caching fuer alle statischen Ressourcen
#spring.web.resources.cache.cachecontrol.no-store=true
#spring.web.resources.cache.cachecontrol.no-cache=true
#spring.web.resources.cache.cachecontrol.must-revalidate=true
#spring.web.resources.cache.cachecontrol.max-age=0
