package de.simon.originality.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.List;

@Schema(description = "The complete and detailed result of a semantic search query.")
public record JsonApiResponseDto(
    @Schema(description = "A high-level summary of the query and its most important findings.")
    Summary summary,

    @Schema(description = "Provides details about how the user's input query was categorized within the knowledge graph.")
    OwnIdeaAnalysis ownIdeaAnalysis,

    @Schema(description = "A list of topic fields that are semantically very similar to the user's query. Do not judge by their names, look into the result papers.")
    List<TopicField> similarTopicFields,

    @Schema(description = "A curated list of surprising yet relevant topic fields that are not obviously related to the query. These are meant to inspire new lines of thought. Do not judge by their names, look into the result papers.")
    List<TopicField> serendipitousConnections,

    @Schema(description = "A list of the most relevant individual documents (e.g., scientific papers) found for the query.")
    List<DetailedResult> detailedSimilarResults
) {

    // --- Nested Records (Method A) ---

    public record Summary(
        @Schema(description = "A pure placeholder title.")
        String inputTitle,
        @Schema(description = "The original query text given to the API, all results are based on it.")
        String inputIdea,
        @Schema(description = "The topics identified for the user's query, they are hierarchical, predicted with HDBSCAN.")
        List<String> mainTopics,
        @Schema(description = "Summaries of the most similar topic fields.")
        List<SummaryTopic> similarTopicFields,
        @Schema(description = "Summaries of the most relevant serendipitous connections.")
        List<SummaryTopic> serendipitousConnections
    ) {}

    public record SummaryTopic(
        @Schema(description = "The name of the cluster.")
        String name,
        @Schema(description = "A short description of the cluster's content.")
        String description,
        @Schema(description = "A score from 0.0 to 1.0 indicating the relevance of this topic to the original query, based on the cosine similarity between input text vector and topic centroid vector. "
        		+ "For the serendipitous clusters, the score is that from its top result, as it is more helpful in that case.")
        @JsonProperty("relevance") 
        float relevanceScore
    ) {}

    public record OwnIdeaAnalysis(
        @Schema(description = "The hierarchical path through the knowledge graph that best represents the query, from broad topics to specific ones, predicted by HDBSCAN models.")
        List<ClusterHierarchyItem> clusterHierarchy
    ) {}

    public record ClusterHierarchyItem(
        @Schema(description = "The unique identifier of the cluster, e.g., 'all_vectors-4-1'.")
        String id,
        @Schema(description = "The human-readable name of the cluster.")
        String name,
        @Schema(description = "The confidence score (probability) that the query belongs to this cluster within its parent, generated by the HDBSCAN models.")
        double score
    ) {}

    public record TopicField(
        @Schema(description = "The unique identifier of the cluster, e.g., 'all_vectors-4-1'.")
        String clusterId,
        @Schema(description = "The human-readable name of the cluster.")
        String clusterName,
        @Schema(description = "A score from 0.0 to 1.0 indicating the relevance of this topic to the original query, based on the cosine similarity between input text vector and topic centroid vector. "
        		+ "For the serendipitous clusters, the score is that from its top result, as it is more helpful in that case.")
        float relevanceScore,
        @Schema(description = "A short description of the cluster's content.")
        String summary,
        @Schema(description = "A list of the most relevant documents found within this cluster.")
        List<DetailedResult> results
    ) {}

    public record DetailedResult(
        @Schema(description = "The unique identifier of the document in the database.")
        String id,
        @Schema(description = "The title of the document.")
        String title,
        @Schema(description = "The abstract or summary of the document.")
        String summary,
        @Schema(description = "A score from 0.0 to 1.0 indicating the relevance of this topic to the original query, based on the cosine similarity between input text vector and entries vector.")
        float score,
        @Schema(description = "A direct URL to the source of the document (e.g., an arXiv or PubMed page). If it does not work, search the internet for the title + summary.")
        String contentUrl
    ) {}
}